%YAML:1.0

dataset: "ULHK"
rosbag_path: "/mnt/d/lsd_data/sad/ulhk/test2.bag"
pickle_path: "/mnt/d/lsd_data/sad/ulhk/test2"

pointcloud_topic: /velodyne_points_0
imu_topic: /imu/data
gps_topic: /navsat/fix

lidar_type: 2                # 1 for Livox serials LiDAR, 2 for Velodyne LiDAR, 3 for ouster LiDAR, 4 for other
scan_line: 32
time_scale: 1e3              # only valid for Velodyne LiDAR(lidar_type=2)
have_gravity: 0              # gravity is excluded in accelerate
acc_unit: 0                  # unit of IMU accelerate, 0 for m/s^2, 1 for g

#transform from lidar frame to vehicle frame, Tv,l
extrinsic_lidar: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1.0, 0.0, 0.0, 0.0,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 1.7,
          0.0, 0.0, 0.0, 1.0]

#transform from imu frame to vehicle frame, Tv,i
extrinsic_imu: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [0.0, 1.0, 0.0, 0.0,
         -1.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 1.98,
          0.0, 0.0, 0.0, 1.0]

#transform from GPS frame to vehicle frame, Tv,g
extrinsic_gps: !!opencv-matrix
   rows: 4
   cols: 4
   dt: d
   data: [1.0, 0.0, 0.0, 0.0,
          0.0, 1.0, 0.0, 0.0,
          0.0, 0.0, 1.0, 0.0,
          0.0, 0.0, 0.0, 1.0]

gps_mode: 2 # mode 2: lat+lon, mode 3: lat+lon+alt
